#!/bin/bash

# EWS Kinit
kinit -kt /etc/security/keytabs/x987731.keytab x987731@NMCORP.NISSAN.BIZ

# Sqoop query for BID_TRD_VS.INCDNT_IVSTGN_EXTRCT_VW
sqoop import --connect jdbc:oracle:thin:@10.78.79.27:55298/OPDBEFLO --username BIDBATCH --password nissan --query "select i1.INCDNT_IVSTGN_RPT_FORM_NM,i1.TRNSCN_DT,i1.ESTMTD_SPD_TX, i1.OTHR_VHCL_INVLV_IN, i1.PRPRTY_DS, i1.TRD_EFCTV_DT, i1.VHCL_ISPCTN_DT, i1.VHCL_ID_NB, i1.VHCL_MK_NM, i1.VHCL_YR_NB, i1.VHCL_NMC_MDL_CD, i1.CLMNT_ST_CD, i1.CLMNT_ST_NM, i1.CLMNT_CNTRY_CD, i1.ADTNL_OBSVTN_TX, i1.VHCL_ADVNCD_TCHLGY_IN, i1.ARBG_OBSVTN_TX, i1.ALGTN_CMPNT_LVL_1_NM, i1.ALGTN_CMPNT_LVL_2_NM, i1.ALGTN_CMPNT_LVL_3_NM, i1.BRAK_SPLMNT_IN, i1.SLSFRC_CASE_ID, i1.CTR_REAR_VHCL_OCPNT_INJRY_IN, i1.INCDNT_OCRNC_TS, i1.VHCL_DRVR_INJRY_DS, i1.CTR_REAR_VHCL_OCPNT_INJRY_DS, i1.LFT_REAR_VHCL_OCPNT_INJRY_DS, i1.OTHR_VHCL_OCPNT_INJRY_DS, i1.RGHT_REAR_VHCL_OCPNT_INJRY_DS, i1.ALGTN_DTL_DS, i1.PRDT_SFTY_RSPNS_DS, i1.DRVR_ARBG_STS_NM, i1.VHCL_DRVR_INJRY_IN, i1.PWRTRN_OBSVTN_TX, i1.EXTR_BDY_INCDNT_TX, i1.INCDNT_IVSTGN_RPT_FORM_ID, CAST('RMVD_ALGD_DFCTV_PRT_TX' as VARCHAR(10)) as RMVD_ALGD_DFCTV_PRT_TX, i1.INTRR_INFRMN_TX, i1.LFT_REAR_ARBG_STS_NM, i1.LFT_REAR_VHCL_OCPNT_INJRY_IN, i1.VHCL_PRKD_DRTN_TX, i1.INCDNT_LCTN_TX, i1.MN_ALGTN_NM, i1.ISPCTN_MLG_NB, i1.PRDT_SFTY_MNTR_IN, i1.PRPRTY_DMG_DS, i1.OTHR_VHCL_DMG_DS, i1.PRSN_INVLVD_NB, i1.OTHR_SPLMNT_RPT_NM, i1.ADTNL_VHCL_INFRMN_TX, i1.OTHR_VHCL_OCPNT_INJRY_IN, i1.OTHR_ARBG_STS_NM, i1.OTHR_VHCL_TYP_TX, i1.VHCL_CRNT_LCTN_TX, i1.INCDNT_SHRT_DS, i1.PRDT_SFTY_RSPNS_TX, i1.RSTRNT_SYSTM_SPLMNT_RPT_IN, i1.RGHT_FRNT_VHCL_OCPNT_INJRY_DS, i1.RGHT_FRNT_ARBG_STS_NM, i1.RGHT_FRNT_VHCL_OCPNT_INJRY_IN, i1.RGHT_REAR_ARBG_STS_NM, i1.RGHT_REAR_VHCL_OCPNT_INJRY_IN, i1.SEAT_RSTRNT_OBSVTN_TX, i1.SCNDRY_ALGTN_NM, i1.STERNG_SPLMNT_RPT_IN, i1.THRML_SPLMNT_RPT_IN, i1.TRNMSN_SPLMNT_RPT_IN, i1.UINTD_ACLRT_SPLMNT_RPT_IN, i1.UNDR_CARG_OBSVTN_TX, i1.ESTMTD_VHCL_SPD_TX, i1.IVSTGN_VIN_ID, i1.WTHR_CNDTN_TX, i1.INCDNT_IVSTGN_RPT_PDF_URL_TX, i1.INCDNT_DTL_DS, i1.CSTMR_RQST_TX, i1.INCDNT_VHCL_MDL_YR_NB, i1.INCDNT_VHCL_NMC_MDL_CD, i1.INCDNT_VHCL_MK_NM, i1.ATCHMT_IN, i1.VHCL_NMC_MDL_NM, i1.DRV_TRN_DS, i1.DRV_TRN_CD, i1.TRM_LVL_DS, i1.MNFCR_DT, i1.NML_PRDCTN_MDL_CD, i1.ORGNL_IN_SVC_DT, i1.TRNMSN_TYP_CD,i1.ENGN_PRFX_CD, i1.TRNMSN_TYP_NM, i1.EMSN_CRFCTN_NB, i1.UPDT_TS, CURRENT_TIMESTAMP as CRTE_TS, CAST(' x987731' as VARCHAR(10)) as CRTE_USR_ID from (select iif.INCDNT_IVSTGN_RPT_FORM_NM, td.CLNDR_DT AS TRNSCN_DT,TED.CLNDR_DT AS TRD_EFCTV_DT, VID.CLNDR_DT AS VHCL_ISPCTN_DT, vd.VHCL_ID_NB, vd.VHCL_NMC_MDL_CD, vd.VHCL_YR_NB, vd.VHCL_MK_NM, sd.st_cd AS CLMNT_ST_CD, sd.st_nm AS CLMNT_ST_NM, CD.CNTRY_CD AS CLMNT_CNTRY_CD, iif.ESTMTD_SPD_TX, iif.OTHR_VHCL_INVLV_IN, iif.PRPRTY_DS, iif.ADTNL_OBSVTN_TX, iif.VHCL_ADVNCD_TCHLGY_IN, iif.ARBG_OBSVTN_TX, iif.ALGTN_CMPNT_LVL_1_NM, iif.ALGTN_CMPNT_LVL_2_NM, iif.ALGTN_CMPNT_LVL_3_NM, iif.BRAK_SPLMNT_IN, iif.SLSFRC_CASE_ID, iif.CTR_REAR_VHCL_OCPNT_INJRY_IN, iif.INCDNT_OCRNC_TS, iif.VHCL_DRVR_INJRY_DS, iif.CTR_REAR_VHCL_OCPNT_INJRY_DS, iif.LFT_REAR_VHCL_OCPNT_INJRY_DS, iif.OTHR_VHCL_OCPNT_INJRY_DS, iif.RGHT_REAR_VHCL_OCPNT_INJRY_DS, iif.ALGTN_DTL_DS, iif.PRDT_SFTY_RSPNS_DS, iif.DRVR_ARBG_STS_NM, iif.VHCL_DRVR_INJRY_IN, iif.PWRTRN_OBSVTN_TX, iif.EXTR_BDY_INCDNT_TX, iif.INCDNT_IVSTGN_RPT_FORM_ID, iif.INTRR_INFRMN_TX, iif.LFT_REAR_ARBG_STS_NM, iif.LFT_REAR_VHCL_OCPNT_INJRY_IN, iif.VHCL_PRKD_DRTN_TX, iif.INCDNT_LCTN_TX, iif.MN_ALGTN_NM, iif.ISPCTN_MLG_NB, iif.PRDT_SFTY_MNTR_IN, iif.PRPRTY_DMG_DS, iif.OTHR_VHCL_DMG_DS, iif.PRSN_INVLVD_NB, iif.OTHR_SPLMNT_RPT_NM, iif.ADTNL_VHCL_INFRMN_TX, iif.OTHR_VHCL_OCPNT_INJRY_IN, iif.OTHR_ARBG_STS_NM, iif.OTHR_VHCL_TYP_TX, iif.VHCL_CRNT_LCTN_TX, iif.INCDNT_SHRT_DS, iif.PRDT_SFTY_RSPNS_TX, iif.RSTRNT_SYSTM_SPLMNT_RPT_IN, iif.RGHT_FRNT_VHCL_OCPNT_INJRY_DS, iif.RGHT_FRNT_ARBG_STS_NM, iif.RGHT_FRNT_VHCL_OCPNT_INJRY_IN, iif.RGHT_REAR_ARBG_STS_NM, iif.RGHT_REAR_VHCL_OCPNT_INJRY_IN, iif.SEAT_RSTRNT_OBSVTN_TX, iif.SCNDRY_ALGTN_NM, iif.STERNG_SPLMNT_RPT_IN, iif.THRML_SPLMNT_RPT_IN, iif.TRNMSN_SPLMNT_RPT_IN, iif.UINTD_ACLRT_SPLMNT_RPT_IN, iif.UNDR_CARG_OBSVTN_TX, iif.ESTMTD_VHCL_SPD_TX, iif.IVSTGN_VIN_ID, iif.WTHR_CNDTN_TX, iif.INCDNT_IVSTGN_RPT_PDF_URL_TX, iif.INCDNT_DTL_DS, iif.CSTMR_RQST_TX, iif.INCDNT_VHCL_MDL_YR_NB, iif.INCDNT_VHCL_NMC_MDL_CD, iif.INCDNT_VHCL_MK_NM, iif.ATCHMT_IN, iif.CRTE_TS AS UPDT_TS, vd.DRV_TRN_CD, vd.DRV_TRN_DS, vd.MNFCR_DT, vd.TRM_LVL_DS, vd.VHCL_NMC_MDL_NM, vd.EMSN_CRFCTN_NB, vd.ENGN_PRFX_CD, vd.NML_PRDCTN_MDL_CD, vd.ORGNL_IN_SVC_DT, vd.TRNMSN_TYP_CD, vd.TRNMSN_TYP_NM from (select iv.INCDNT_DM_KY, iv.INCDNT_TYP_DM_KY, max(iv.trd_dm_ky) as max_trd_dm_ky from (select iig.INCDNT_DM_KY, iig.INCDNT_TYP_DM_KY, iig.TRD_DM_KY, iig.TRNSCN_DT_KY, iig.TRD_EFCTV_DT_KY, iig.VHCL_ISPCTN_DT_KY, iig.VHCL_DM_KY, iig.VHCL_MDL_DM_KY, iig.CLMNT_ST_DM_KY, iig.CLMNT_CNTRY_DM_KY, iig.ESTMTD_SPD_TX, iig.OTHR_VHCL_INVLV_IN, iig.PRPRTY_DS, iig.ADTNL_OBSVTN_TX, iig.VHCL_ADVNCD_TCHLGY_IN, iig.ARBG_OBSVTN_TX, iig.ALGTN_CMPNT_LVL_1_NM, iig.ALGTN_CMPNT_LVL_2_NM, iig.ALGTN_CMPNT_LVL_3_NM, iig.BRAK_SPLMNT_IN, iig.SLSFRC_CASE_ID, iig.CTR_REAR_VHCL_OCPNT_INJRY_IN, iig.INCDNT_OCRNC_TS, iig.VHCL_DRVR_INJRY_DS, iig.CTR_REAR_VHCL_OCPNT_INJRY_DS, iig.LFT_REAR_VHCL_OCPNT_INJRY_DS, iig.OTHR_VHCL_OCPNT_INJRY_DS, iig.RGHT_REAR_VHCL_OCPNT_INJRY_DS, iig.ALGTN_DTL_DS, iig.PRDT_SFTY_RSPNS_DS, iig.DRVR_ARBG_STS_NM, iig.VHCL_DRVR_INJRY_IN, iig.PWRTRN_OBSVTN_TX, iig.EXTR_BDY_INCDNT_TX, iig.INCDNT_IVSTGN_RPT_FORM_ID, iig.INTRR_INFRMN_TX, iig.LFT_REAR_ARBG_STS_NM, iig.LFT_REAR_VHCL_OCPNT_INJRY_IN, iig.VHCL_PRKD_DRTN_TX, iig.INCDNT_LCTN_TX, iig.MN_ALGTN_NM, iig.ISPCTN_MLG_NB, iig.PRDT_SFTY_MNTR_IN, iig.INCDNT_IVSTGN_RPT_FORM_NM, iig.PRPRTY_DMG_DS, iig.OTHR_VHCL_DMG_DS, iig.PRSN_INVLVD_NB, iig.OTHR_SPLMNT_RPT_NM, iig.ADTNL_VHCL_INFRMN_TX, iig.OTHR_VHCL_OCPNT_INJRY_IN, iig.OTHR_ARBG_STS_NM, iig.OTHR_VHCL_TYP_TX, iig.VHCL_CRNT_LCTN_TX, iig.INCDNT_SHRT_DS, iig.PRDT_SFTY_RSPNS_TX, iig.RSTRNT_SYSTM_SPLMNT_RPT_IN, iig.RGHT_FRNT_VHCL_OCPNT_INJRY_DS, iig.RGHT_FRNT_ARBG_STS_NM, iig.RGHT_FRNT_VHCL_OCPNT_INJRY_IN, iig.RGHT_REAR_ARBG_STS_NM, iig.RGHT_REAR_VHCL_OCPNT_INJRY_IN, iig.SEAT_RSTRNT_OBSVTN_TX, iig.SCNDRY_ALGTN_NM, iig.STERNG_SPLMNT_RPT_IN, iig.THRML_SPLMNT_RPT_IN, iig.TRNMSN_SPLMNT_RPT_IN, iig.UINTD_ACLRT_SPLMNT_RPT_IN, iig.UNDR_CARG_OBSVTN_TX, iig.ESTMTD_VHCL_SPD_TX, iig.IVSTGN_VIN_ID, iig.WTHR_CNDTN_TX, iig.INCDNT_IVSTGN_RPT_PDF_URL_TX, iig.INCDNT_DTL_DS, iig.CSTMR_RQST_TX, iig.INCDNT_VHCL_MDL_YR_NB, iig.INCDNT_VHCL_NMC_MDL_CD, iig.INCDNT_VHCL_MK_NM, iig.ATCHMT_IN, iig.CNSMR_AFR_INSTNC_CN, iig.CRTE_TS, iig.CRTE_USR_ID from (select c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY, max(c.TRNSCN_DT_KY) as iir_tns_dt from ( SELECT D.INCDNT_DM_KY, D.INCDNT_TYP_DM_KY, D.TRNSCN_DT_KY FROM BID_LGL_IIR.INCDNT_IVSTGN_FC D ORDER BY D.TRNSCN_DT_KY DESC ) c group by c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY) list, BID_LGL_IIR.INCDNT_IVSTGN_FC iig where list.INCDNT_DM_KY = iig.INCDNT_DM_KY and list.INCDNT_TYP_DM_KY = iig.INCDNT_TYP_DM_KY and list.iir_TNS_DT = iig.TRNSCN_DT_KY) iv group by iv.INCDNT_DM_KY, iv.INCDNT_TYP_DM_KY) a join (select iih.INCDNT_DM_KY, iih.INCDNT_TYP_DM_KY, iih.TRD_DM_KY, iih.TRNSCN_DT_KY, iih.TRD_EFCTV_DT_KY, iih.VHCL_ISPCTN_DT_KY, iih.VHCL_DM_KY, iih.VHCL_MDL_DM_KY, iih.CLMNT_ST_DM_KY, iih.CLMNT_CNTRY_DM_KY, iih.ESTMTD_SPD_TX, iih.OTHR_VHCL_INVLV_IN, iih.PRPRTY_DS, iih.ADTNL_OBSVTN_TX, iih.VHCL_ADVNCD_TCHLGY_IN, iih.ARBG_OBSVTN_TX, iih.ALGTN_CMPNT_LVL_1_NM, iih.ALGTN_CMPNT_LVL_2_NM, iih.ALGTN_CMPNT_LVL_3_NM, iih.BRAK_SPLMNT_IN, iih.SLSFRC_CASE_ID, iih.CTR_REAR_VHCL_OCPNT_INJRY_IN, iih.INCDNT_OCRNC_TS, iih.VHCL_DRVR_INJRY_DS, iih.CTR_REAR_VHCL_OCPNT_INJRY_DS, iih.LFT_REAR_VHCL_OCPNT_INJRY_DS, iih.OTHR_VHCL_OCPNT_INJRY_DS, iih.RGHT_REAR_VHCL_OCPNT_INJRY_DS, iih.ALGTN_DTL_DS, iih.PRDT_SFTY_RSPNS_DS, iih.DRVR_ARBG_STS_NM, iih.VHCL_DRVR_INJRY_IN, iih.PWRTRN_OBSVTN_TX, iih.EXTR_BDY_INCDNT_TX, iih.INCDNT_IVSTGN_RPT_FORM_ID, iih.INTRR_INFRMN_TX, iih.LFT_REAR_ARBG_STS_NM, iih.LFT_REAR_VHCL_OCPNT_INJRY_IN, iih.VHCL_PRKD_DRTN_TX, iih.INCDNT_LCTN_TX, iih.MN_ALGTN_NM, iih.ISPCTN_MLG_NB, iih.PRDT_SFTY_MNTR_IN, iih.INCDNT_IVSTGN_RPT_FORM_NM, iih.PRPRTY_DMG_DS, iih.OTHR_VHCL_DMG_DS, iih.PRSN_INVLVD_NB, iih.OTHR_SPLMNT_RPT_NM, iih.ADTNL_VHCL_INFRMN_TX, iih.OTHR_VHCL_OCPNT_INJRY_IN, iih.OTHR_ARBG_STS_NM, iih.OTHR_VHCL_TYP_TX, iih.VHCL_CRNT_LCTN_TX, iih.INCDNT_SHRT_DS, iih.PRDT_SFTY_RSPNS_TX, iih.RSTRNT_SYSTM_SPLMNT_RPT_IN, iih.RGHT_FRNT_VHCL_OCPNT_INJRY_DS, iih.RGHT_FRNT_ARBG_STS_NM, iih.RGHT_FRNT_VHCL_OCPNT_INJRY_IN, iih.RGHT_REAR_ARBG_STS_NM, iih.RGHT_REAR_VHCL_OCPNT_INJRY_IN, iih.SEAT_RSTRNT_OBSVTN_TX, iih.SCNDRY_ALGTN_NM, iih.STERNG_SPLMNT_RPT_IN, iih.THRML_SPLMNT_RPT_IN, iih.TRNMSN_SPLMNT_RPT_IN, iih.UINTD_ACLRT_SPLMNT_RPT_IN, iih.UNDR_CARG_OBSVTN_TX, iih.ESTMTD_VHCL_SPD_TX, iih.IVSTGN_VIN_ID, iih.WTHR_CNDTN_TX, iih.INCDNT_IVSTGN_RPT_PDF_URL_TX, iih.INCDNT_DTL_DS, iih.CSTMR_RQST_TX, iih.INCDNT_VHCL_MDL_YR_NB, iih.INCDNT_VHCL_NMC_MDL_CD, iih.INCDNT_VHCL_MK_NM, iih.ATCHMT_IN, iih.CNSMR_AFR_INSTNC_CN, iih.CRTE_TS, iih.CRTE_USR_ID from (select c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY, max(c.TRNSCN_DT_KY) as iir_tns_dt from ( SELECT D.INCDNT_DM_KY, D.INCDNT_TYP_DM_KY, D.TRNSCN_DT_KY FROM BID_LGL_IIR.INCDNT_IVSTGN_FC D ORDER BY D.TRNSCN_DT_KY DESC ) c group by c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY) list, BID_LGL_IIR.INCDNT_IVSTGN_FC iih where list.INCDNT_DM_KY = iih.INCDNT_DM_KY and list.INCDNT_TYP_DM_KY = iih.INCDNT_TYP_DM_KY and list.iir_TNS_DT = iih.TRNSCN_DT_KY)iif on a.INCDNT_DM_KY = iif.INCDNT_DM_KY and a.INCDNT_TYP_DM_KY = iif.INCDNT_TYP_DM_KY and a.max_trd_dm_ky = iif.trd_dm_ky left outer join bid_veh.vhcl_dm vd on vd.VHCL_DM_KY = iif.VHCL_DM_KY and vd.VHCL_DM_END_DT > sysdate left outer join BID_VEH.ST_DM sd on sd.ST_DM_KY = iif.CLMNT_ST_DM_KY left outer join BID_VEH.CNTRY_DM cd on cd.CNTRY_DM_KY = iif.CLMNT_CNTRY_DM_KY left outer join NEDW_DIM.CLNDR_DM ted on ted.clndr_dm_ky = IIF.TRD_EFCTV_DT_KY left outer join NEDW_DIM.CLNDR_DM td on td.clndr_dm_ky = IIF.TRNSCN_DT_KY left outer join NEDW_DIM.CLNDR_DM VID on VID.clndr_dm_ky = iif.VHCL_ISPCTN_DT_KY)i1 WHERE \$CONDITIONS" --target-dir hdfs://bdestg/data/lgl_iir/raw/incdnt_ivstgn_raw --fields-terminated-by '\001' --null-string '' --null-non-string '' --escaped-by '\\'  --delete-target-dir -m 1

 # Sqoop query for BID_TRD_VS.INCDNT_IVSTGN_TRD_EXTRCT_VW
 sqoop import --connect jdbc:oracle:thin:@10.78.79.27:55298/OPDBEFLO --query "select INCDNT_IVSTGN_RPT_FORM_NM,TRD_CD,TRD_CD_DS,CAST('x987731' as VARCHAR(10)) as CRTE_USR_ID,CURRENT_TIMESTAMP as CRTE_TS,CMPST_KY,UPDT_TS from (select iif.INCDNT_IVSTGN_RPT_FORM_NM || trd.TRD_CD as CMPST_KY,
 iif.INCDNT_IVSTGN_RPT_FORM_NM,
  trd.TRD_CD,
  trd.TRD_CD_DS,
  iif.crte_ts AS UPDT_TS
 from
 (select iif.INCDNT_DM_KY,
 iif.INCDNT_TYP_DM_KY,
 iif.TRD_DM_KY,
 iif.TRNSCN_DT_KY,
 iif.TRD_EFCTV_DT_KY,
 iif.VHCL_ISPCTN_DT_KY,
 iif.VHCL_DM_KY,
 iif.VHCL_MDL_DM_KY,
 iif.CLMNT_ST_DM_KY,
 iif.CLMNT_CNTRY_DM_KY,
 iif.ESTMTD_SPD_TX,
 iif.OTHR_VHCL_INVLV_IN,
 iif.PRPRTY_DS,
 iif.ADTNL_OBSVTN_TX,
 iif.VHCL_ADVNCD_TCHLGY_IN,
 iif.ARBG_OBSVTN_TX,
 iif.ALGTN_CMPNT_LVL_1_NM,
 iif.ALGTN_CMPNT_LVL_2_NM,
 iif.ALGTN_CMPNT_LVL_3_NM,
 iif.BRAK_SPLMNT_IN,
 iif.SLSFRC_CASE_ID,
 iif.CTR_REAR_VHCL_OCPNT_INJRY_IN,
 iif.INCDNT_OCRNC_TS,
 iif.VHCL_DRVR_INJRY_DS,
 iif.CTR_REAR_VHCL_OCPNT_INJRY_DS,
 iif.LFT_REAR_VHCL_OCPNT_INJRY_DS,
 iif.OTHR_VHCL_OCPNT_INJRY_DS,
 iif.RGHT_REAR_VHCL_OCPNT_INJRY_DS,
 iif.ALGTN_DTL_DS,
 iif.PRDT_SFTY_RSPNS_DS,
 iif.DRVR_ARBG_STS_NM,
 iif.VHCL_DRVR_INJRY_IN,
 iif.PWRTRN_OBSVTN_TX,
 iif.EXTR_BDY_INCDNT_TX,
 iif.INCDNT_IVSTGN_RPT_FORM_ID,
 iif.RMVD_ALGD_DFCTV_PRT_TX,
 iif.INTRR_INFRMN_TX,
 iif.LFT_REAR_ARBG_STS_NM,
 iif.LFT_REAR_VHCL_OCPNT_INJRY_IN,
 iif.VHCL_PRKD_DRTN_TX,
 iif.INCDNT_LCTN_TX,
 iif.MN_ALGTN_NM,
 iif.ISPCTN_MLG_NB,
 iif.PRDT_SFTY_MNTR_IN,
 iif.INCDNT_IVSTGN_RPT_FORM_NM,
 iif.PRPRTY_DMG_DS,
 iif.OTHR_VHCL_DMG_DS,
 iif.PRSN_INVLVD_NB,
 iif.OTHR_SPLMNT_RPT_NM,
 iif.ADTNL_VHCL_INFRMN_TX,
 iif.OTHR_VHCL_OCPNT_INJRY_IN,
 iif.OTHR_ARBG_STS_NM,
 iif.OTHR_VHCL_TYP_TX,
 iif.VHCL_CRNT_LCTN_TX,
 iif.INCDNT_SHRT_DS,
 iif.PRDT_SFTY_RSPNS_TX,
 iif.RSTRNT_SYSTM_SPLMNT_RPT_IN,
 iif.RGHT_FRNT_VHCL_OCPNT_INJRY_DS,
 iif.RGHT_FRNT_ARBG_STS_NM,
 iif.RGHT_FRNT_VHCL_OCPNT_INJRY_IN,
 iif.RGHT_REAR_ARBG_STS_NM,
 iif.RGHT_REAR_VHCL_OCPNT_INJRY_IN,
 iif.SEAT_RSTRNT_OBSVTN_TX,
 iif.SCNDRY_ALGTN_NM,
 iif.STERNG_SPLMNT_RPT_IN,
 iif.THRML_SPLMNT_RPT_IN,
 iif.TRNMSN_SPLMNT_RPT_IN,
 iif.UINTD_ACLRT_SPLMNT_RPT_IN,
 iif.UNDR_CARG_OBSVTN_TX,
 iif.ESTMTD_VHCL_SPD_TX,
 iif.IVSTGN_VIN_ID,
 iif.WTHR_CNDTN_TX,
 iif.INCDNT_IVSTGN_RPT_PDF_URL_TX,
 iif.INCDNT_DTL_DS,
 iif.CSTMR_RQST_TX,
 iif.INCDNT_VHCL_MDL_YR_NB,
 iif.INCDNT_VHCL_NMC_MDL_CD,
 iif.INCDNT_VHCL_MK_NM,
 iif.ATCHMT_IN,
 iif.CNSMR_AFR_INSTNC_CN,
 iif.CRTE_TS,
 iif.CRTE_USR_ID
 from
 (select c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY, max(c.TRNSCN_DT_KY) as iir_tns_dt
 from (
     SELECT D.INCDNT_DM_KY, D.INCDNT_TYP_DM_KY, D.TRNSCN_DT_KY
     FROM BID_LGL_IIR.INCDNT_IVSTGN_FC D
     ORDER BY D.TRNSCN_DT_KY DESC ) c
 group by c.iNCDNT_DM_KY, c.INCDNT_TYP_DM_KY) list,
 BID_LGL_IIR.INCDNT_IVSTGN_FC iif
 where list.INCDNT_DM_KY = iif.INCDNT_DM_KY
 and list.INCDNT_TYP_DM_KY = iif.INCDNT_TYP_DM_KY
 and list.iir_TNS_DT = iif.TRNSCN_DT_KY) iif
 left outer join BID_TRD.TRD_DM trd on trd.TRD_DM_KY = iif.TRD_DM_KY) WHERE \$CONDITIONS" --target-dir hdfs://bdestg/data/lgl_iir/raw/incdnt_ivstgn_trd_raw --fields-terminated-by '\001' --null-string '' --null-non-string '' --escaped-by '\\' --check-column UPDT_TS --incremental 'lastmodified' --hive-drop-import-delims --merge-key INCDNT_IVSTGN_RPT_FORM_NM --last-value '0001-01-01 00:00:00.000' --username 'BIDBATCH' --password 'nissan' -m 1

hive -f convert_raw_to_base_iir.hql
