#!/bin/bash
> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as dbsro__repair_order_history__date, count(*) as recordscount FROM dbsro.repair_order_history group by DATE(updt_ts) order by dbsro__repair_order_history__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as dbsro__repair_order_line_history__date count(*) as recordscount FROM dbsro__repair_order_line_history group by DATE(updt_ts) order by dbsro__repair_order_line_history__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__pfp_engnr__date count(*) as recordscount FROM equip__pfp_engnr group by DATE(updt_ts) order by equip__pfp_engnr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cmpnt_grp__date count(*) as recordscount FROM equip__cmpnt_grp group by DATE(updt_ts) order by equip__cmpnt_grp__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cstmr_stsfcn_team__date count(*) as recordscount FROM equip__cstmr_stsfcn_team group by DATE(updt_ts) order by equip__cstmr_stsfcn_team__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fld_engrng_stf__date count(*) as recordscount FROM equip__fld_engrng_stf group by DATE(updt_ts) order by equip__fld_engrng_stf__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fld_qlty_role__date count(*) as recordscount FROM equip__fld_qlty_role group by DATE(updt_ts) order by equip__fld_qlty_role__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fqi_grp__date count(*) as recordscount FROM equip__fqi_grp group by DATE(updt_ts) order by equip__fqi_grp__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fqi_pfp__date count(*) as recordscount FROM equip__fqi_pfp group by DATE(updt_ts) order by equip__fqi_pfp__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fqi_rpsntv__date count(*) as recordscount FROM equip__fqi_rpsntv group by DATE(updt_ts) order by equip__fqi_rpsntv__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cstmr_stsfcn_team_mbr__date count(*) as recordscount FROM equip__cstmr_stsfcn_team_mbr group by DATE(updt_ts) order by equip__cstmr_stsfcn_team_mbr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__pfp_rspsbl_engnr__date count(*) as recordscount FROM equip__pfp_rspsbl_engnr group by DATE(updt_ts) order by equip__pfp_rspsbl_engnr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fqi_base_mdl__date count(*) as recordscount FROM equip__fqi_base_mdl group by DATE(updt_ts) order by equip__fqi_base_mdl__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__fqi_crnt_mdl__date count(*) as recordscount FROM equip__fqi_crnt_mdl group by DATE(updt_ts) order by equip__fqi_crnt_mdl__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds_cmltv__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds_cmltv group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds_cmltv__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_cmltv__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_cmltv group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_cmltv__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_vms_cms__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_vms_cms group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs_vms_cms__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds_vms_cms__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds_vms_cms group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds_vms_cms__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds_dflt_fltrs__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ir_cmbnd_vhcl_clm_lmtd_flds__date count(*) as recordscount FROM equip__ir_cmbnd_vhcl_clm_lmtd_flds group by DATE(updt_ts) order by equip__ir_cmbnd_vhcl_clm_lmtd_flds__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__aves_base__date count(*) as recordscount FROM equip__aves_base group by DATE(updt_ts) order by equip__aves_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__aves_vhcl_solr__date count(*) as recordscount FROM equip__aves_vhcl_solr group by DATE(updt_ts) order by equip__aves_vhcl_solr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__CMDTA_BASE__date count(*) as recordscount FROM drive__CMDTA_BASE group by DATE(crte_ts) order by drive__CMDTA_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__PRTS_DTL_CMDTA_BASE__date count(*) as recordscount FROM drive__PRTS_DTL_CMDTA_BASE group by DATE(crte_ts) order by drive__PRTS_DTL_CMDTA_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__PLNT_CD_ARAY_BASE__date count(*) as recordscount FROM drive__PLNT_CD_ARAY_BASE group by DATE(crte_ts) order by drive__PLNT_CD_ARAY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__HS_BASE__date count(*) as recordscount FROM drive__HS_BASE group by DATE(crte_ts) order by drive__HS_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__RQST_PRT_MVMNT_BASE__date count(*) as recordscount FROM drive__RQST_PRT_MVMNT_BASE group by DATE(crte_ts) order by drive__RQST_PRT_MVMNT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__ADTNL_PFP_ARAY_BASE__date count(*) as recordscount FROM drive__ADTNL_PFP_ARAY_BASE group by DATE(crte_ts) order by drive__ADTNL_PFP_ARAY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__MDL_CD_ARAY_BASE__date count(*) as recordscount FROM drive__MDL_CD_ARAY_BASE group by DATE(crte_ts) order by drive__MDL_CD_ARAY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__BIC_BASE__date count(*) as recordscount FROM drive__BIC_BASE group by DATE(crte_ts) order by drive__BIC_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__DPRTMT_BASE__date count(*) as recordscount FROM drive__DPRTMT_BASE group by DATE(crte_ts) order by drive__DPRTMT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__DSGN_NT_CMDTA_BASE__date count(*) as recordscount FROM drive__DSGN_NT_CMDTA_BASE group by DATE(crte_ts) order by drive__DSGN_NT_CMDTA_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__DSGN_NT_ADR_BASE__date count(*) as recordscount FROM drive__DSGN_NT_ADR_BASE group by DATE(crte_ts) order by drive__DSGN_NT_ADR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__USR_INFRMN_BASE__date count(*) as recordscount FROM drive__USR_INFRMN_BASE group by DATE(crte_ts) order by drive__USR_INFRMN_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__USR_ROLE_BASE__date count(*) as recordscount FROM drive__USR_ROLE_BASE group by DATE(crte_ts) order by drive__USR_ROLE_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__VHCL_BASE__date count(*) as recordscount FROM drive__VHCL_BASE group by DATE(crte_ts) order by drive__VHCL_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__RQST_BASE__date count(*) as recordscount FROM drive__RQST_BASE group by DATE(crte_ts) order by drive__RQST_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__ADR_BASE__date count(*) as recordscount FROM drive__ADR_BASE group by DATE(crte_ts) order by drive__ADR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__MDL_YR_ARAY_BASE__date count(*) as recordscount FROM drive__MDL_YR_ARAY_BASE group by DATE(crte_ts) order by drive__MDL_YR_ARAY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__HRZNTL_DPLYMT_MDL_ARAY_BASE__date count(*) as recordscount FROM drive__HRZNTL_DPLYMT_MDL_ARAY_BASE group by DATE(crte_ts) order by drive__HRZNTL_DPLYMT_MDL_ARAY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__PRJCT_BASE__date count(*) as recordscount FROM drive__PRJCT_BASE group by DATE(crte_ts) order by drive__PRJCT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__ADPTN_DATA_BASE__date count(*) as recordscount FROM drive__ADPTN_DATA_BASE group by DATE(crte_ts) order by drive__ADPTN_DATA_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__MRKT_RPLY_PBLC_BASE__date count(*) as recordscount FROM drive__MRKT_RPLY_PBLC_BASE group by DATE(crte_ts) order by drive__MRKT_RPLY_PBLC_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__WRKFLW_BASE__date count(*) as recordscount FROM drive__WRKFLW_BASE group by DATE(crte_ts) order by drive__WRKFLW_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__MRKT_RPLY_BASE__date count(*) as recordscount FROM drive__MRKT_RPLY_BASE group by DATE(crte_ts) order by drive__MRKT_RPLY_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as drive__TECH_RPT_BASE__date count(*) as recordscount FROM drive__TECH_RPT_BASE group by DATE(crte_ts) order by drive__TECH_RPT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as odi__nhtsa_ivstgn_base__date count(*) as recordscount FROM odi__nhtsa_ivstgn_base group by DATE(crte_ts) order by odi__nhtsa_ivstgn_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as odi__nhtsa_rcl_base__date count(*) as recordscount FROM odi__nhtsa_rcl_base group by DATE(crte_ts) order by odi__nhtsa_rcl_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as odi__nhtsa_svc_bltn_base__date count(*) as recordscount FROM odi__nhtsa_svc_bltn_base group by DATE(crte_ts) order by odi__nhtsa_svc_bltn_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as odi__nhtsa_cnsmr_cmplnt_base__date count(*) as recordscount FROM odi__nhtsa_cnsmr_cmplnt_base group by DATE(crte_ts) order by odi__nhtsa_cnsmr_cmplnt_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as rcl__rcl_base__date count(*) as recordscount FROM rcl__rcl_base group by DATE(crte_ts) order by rcl__rcl_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as rcl__vhcl_rcl_base__date count(*) as recordscount FROM rcl__vhcl_rcl_base group by DATE(crte_ts) order by rcl__vhcl_rcl_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(repair_date) as equip__adhoc_claim_dm__date count(*) as recordscount FROM equip__adhoc_claim_dm group by DATE(repair_date) order by equip__adhoc_claim_dm__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(reportdate) as equip__adhoc_claim__date count(*) as recordscount FROM equip__adhoc_claim group by DATE(reportdate) order by equip__adhoc_claim__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(rundate) as equip__adhoc_comment_cust__date count(*) as recordscount FROM equip__adhoc_comment_cust group by DATE(rundate) order by equip__adhoc_comment_cust__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(rundate) as equip__adhoc_comment_tech__date count(*) as recordscount FROM equip__adhoc_comment_tech group by DATE(rundate) order by equip__adhoc_comment_tech__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(processdate) as equip__adhoc_cpv__date count(*) as recordscount FROM equip__adhoc_cpv group by DATE(processdate) order by equip__adhoc_cpv__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as equip__adhoc_gcar_project__date count(*) as recordscount FROM equip__adhoc_gcar_project group by DATE(crte_ts) order by equip__adhoc_gcar_project__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as equip__adhoc_gcar_req__date count(*) as recordscount FROM equip__adhoc_gcar_req group by DATE(crte_ts) order by equip__adhoc_gcar_req__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(reportdate) as equip__adhoc_gcarmaster__date count(*) as recordscount FROM equip__adhoc_gcarmaster group by DATE(reportdate) order by equip__adhoc_gcarmaster__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(update_dt) as equip__adhoc_opcode__date count(*) as recordscount FROM equip__adhoc_opcode group by DATE(update_dt) order by equip__adhoc_opcode__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(update_dt) as equip__adhoc_part__date count(*) as recordscount FROM equip__adhoc_part group by DATE(update_dt) order by equip__adhoc_part__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(reportdate) as equip__adhoc_tracking_CVTClaims_F1__date count(*) as recordscount FROM equip__adhoc_tracking_CVTClaims_F1 group by DATE(reportdate) order by equip__adhoc_tracking_CVTClaims_F1__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(reportdate) as equip__adhoc_tracking_CVTClaims_FKJK__date count(*) as recordscount FROM equip__adhoc_tracking_CVTClaims_FKJK group by DATE(reportdate) order by equip__adhoc_tracking_CVTClaims_FKJK__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(update_dt) as equip__adhoc_tracking_CVTPartUse_F1__date count(*) as recordscount FROM equip__adhoc_tracking_CVTPartUse_F1 group by DATE(update_dt) order by equip__adhoc_tracking_CVTPartUse_F1__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(update_dt) as equip__adhoc_tracking_CVTPartUse_FKJK__date count(*) as recordscount FROM equip__adhoc_tracking_CVTPartUse_FKJK group by DATE(update_dt) order by equip__adhoc_tracking_CVTPartUse_FKJK__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(reportdate) as equip__adhoc_vehicle__date count(*) as recordscount FROM equip__adhoc_vehicle group by DATE(reportdate) order by equip__adhoc_vehicle__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(rundate) as equip__adhoc_vehicle_gcar_conspfp_cov__date count(*) as recordscount FROM equip__adhoc_vehicle_gcar_conspfp_cov group by DATE(rundate) order by equip__adhoc_vehicle_gcar_conspfp_cov__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(rundate) as equip__adhoc_vehicle_navi__date count(*) as recordscount FROM equip__adhoc_vehicle_navi group by DATE(rundate) order by equip__adhoc_vehicle_navi__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(opcode_update_dt) as equip__adhoc_vehicleopcode__date count(*) as recordscount FROM equip__adhoc_vehicleopcode group by DATE(opcode_update_dt) order by equip__adhoc_vehicleopcode__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(part_update_dt) as equip__adhoc_vehiclepart__date count(*) as recordscount FROM equip__adhoc_vehiclepart group by DATE(part_update_dt) order by equip__adhoc_vehiclepart__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__nsn_trbl_base__date count(*) as recordscount FROM vhcl_qlty_srvy__nsn_trbl_base group by DATE(crte_ts) order by vhcl_qlty_srvy__nsn_trbl_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__nsn_trbl_rspsbl_engnr_base__date count(*) as recordscount FROM vhcl_qlty_srvy__nsn_trbl_rspsbl_engnr_base group by DATE(crte_ts) order by vhcl_qlty_srvy__nsn_trbl_rspsbl_engnr_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__qcs_adtnl_rspns_base__date count(*) as recordscount FROM vhcl_qlty_srvy__qcs_adtnl_rspns_base group by DATE(crte_ts) order by vhcl_qlty_srvy__qcs_adtnl_rspns_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__qcs_ck_bx_base__date count(*) as recordscount FROM vhcl_qlty_srvy__qcs_ck_bx_base group by DATE(crte_ts) order by vhcl_qlty_srvy__qcs_ck_bx_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__qcs_rspndt_base__date count(*) as recordscount FROM vhcl_qlty_srvy__qcs_rspndt_base group by DATE(crte_ts) order by vhcl_qlty_srvy__qcs_rspndt_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(crte_ts) as vhcl_qlty_srvy__qcs_rspns_base__date count(*) as recordscount FROM vhcl_qlty_srvy__qcs_rspns_base group by DATE(crte_ts) order by vhcl_qlty_srvy__qcs_rspns_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cnsmr_afr_cmnt_base__date count(*) as recordscount FROM equip__cnsmr_afr_cmnt_base group by DATE(updt_ts) order by equip__cnsmr_afr_cmnt_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cnsmr_afr_base__date count(*) as recordscount FROM equip__cnsmr_afr_base group by DATE(updt_ts) order by equip__cnsmr_afr_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cnsmr_afr_trd_cncrn_base__date count(*) as recordscount FROM equip__cnsmr_afr_trd_cncrn_base group by DATE(updt_ts) order by equip__cnsmr_afr_trd_cncrn_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__cnsmr_afr_vhcl_solr__date count(*) as recordscount FROM equip__cnsmr_afr_vhcl_solr group by DATE(updt_ts) order by equip__cnsmr_afr_vhcl_solr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__tchln_base__date count(*) as recordscount FROM equip__tchln_base group by DATE(updt_ts) order by equip__tchln_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__tchln_cmnt_base__date count(*) as recordscount FROM equip__tchln_cmnt_base group by DATE(updt_ts) order by equip__tchln_cmnt_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__tchln_trd_base__date count(*) as recordscount FROM equip__tchln_trd_base group by DATE(updt_ts) order by equip__tchln_trd_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__tchln_vhcl_solr__date count(*) as recordscount FROM equip__tchln_vhcl_solr group by DATE(updt_ts) order by equip__tchln_vhcl_solr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__inspct_base__date count(*) as recordscount FROM equip__inspct_base group by DATE(updt_ts) order by equip__inspct_base__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__inspct_vhcl_solr__date count(*) as recordscount FROM equip__inspct_vhcl_solr group by DATE(updt_ts) order by equip__inspct_vhcl_solr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__WRNTY_CVRG_CLAS_BASE__date count(*) as recordscount FROM equip__WRNTY_CVRG_CLAS_BASE group by DATE(updt_ts) order by equip__WRNTY_CVRG_CLAS_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__ASGND_ENGNR_BASE__date count(*) as recordscount FROM equip__ASGND_ENGNR_BASE group by DATE(updt_ts) order by equip__ASGND_ENGNR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__DSTRBR_BASE__date count(*) as recordscount FROM equip__DSTRBR_BASE group by DATE(updt_ts) order by equip__DSTRBR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__SVC_OPRTN_BASE__date count(*) as recordscount FROM equip__SVC_OPRTN_BASE group by DATE(updt_ts) order by equip__SVC_OPRTN_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__SVC_PRT_BASE__date count(*) as recordscount FROM equip__SVC_PRT_BASE group by DATE(updt_ts) order by equip__SVC_PRT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__WRNTY_CMNT_BASE__date count(*) as recordscount FROM equip__WRNTY_CMNT_BASE group by DATE(updt_ts) order by equip__WRNTY_CMNT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__PNC_BASE__date count(*) as recordscount FROM equip__PNC_BASE group by DATE(updt_ts) order by equip__PNC_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__PFP_BASE__date count(*) as recordscount FROM equip__PFP_BASE group by DATE(updt_ts) order by equip__PFP_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__VHCL_SYMPTM_BASE__date count(*) as recordscount FROM equip__VHCL_SYMPTM_BASE group by DATE(updt_ts) order by equip__VHCL_SYMPTM_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__VHCL_TRBL_BASE__date count(*) as recordscount FROM equip__VHCL_TRBL_BASE group by DATE(updt_ts) order by equip__VHCL_TRBL_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__WRNTY_CLM_BASE__date count(*) as recordscount FROM equip__WRNTY_CLM_BASE group by DATE(updt_ts) order by equip__WRNTY_CLM_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__WRNTY_BSNS_TYP_BASE__date count(*) as recordscount FROM equip__WRNTY_BSNS_TYP_BASE group by DATE(updt_ts) order by equip__WRNTY_BSNS_TYP_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__VNDR_BASE__date count(*) as recordscount FROM equip__VNDR_BASE group by DATE(updt_ts) order by equip__VNDR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__VHCL_ENGN_MDL_BASE__date count(*) as recordscount FROM equip__VHCL_ENGN_MDL_BASE group by DATE(updt_ts) order by equip__VHCL_ENGN_MDL_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__PRT_BASE__date count(*) as recordscount FROM equip__PRT_BASE group by DATE(updt_ts) order by equip__PRT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__PRDCTN_MDL_SRS_BASE__date count(*) as recordscount FROM equip__PRDCTN_MDL_SRS_BASE group by DATE(updt_ts) order by equip__PRDCTN_MDL_SRS_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__OPRTN_LCTN_BASE__date count(*) as recordscount FROM equip__OPRTN_LCTN_BASE group by DATE(updt_ts) order by equip__OPRTN_LCTN_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__MDPRT_ASGNMT_BASE__date count(*) as recordscount FROM equip__MDPRT_ASGNMT_BASE group by DATE(updt_ts) order by equip__MDPRT_ASGNMT_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__LBR_OPRTN_BASE__date count(*) as recordscount FROM equip__LBR_OPRTN_BASE group by DATE(updt_ts) order by equip__LBR_OPRTN_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__GLBL_SPLR_BASE__date count(*) as recordscount FROM equip__GLBL_SPLR_BASE group by DATE(updt_ts) order by equip__GLBL_SPLR_BASE__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__wrnty_clm_vhcl_solr__date count(*) as recordscount FROM equip__wrnty_clm_vhcl_solr group by DATE(updt_ts) order by equip__wrnty_clm_vhcl_solr__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(updt_ts) as equip__mileage__date count(*) as recordscount FROM equip__mileage group by DATE(updt_ts) order by equip__mileage__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(ls_up_tm_stmp) as equip__vhcl__date count(*) as recordscount FROM equip__vhcl group by DATE(ls_up_tm_stmp) order by equip__vhcl__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(ls_up_tm_stmp) as equip__DLR_DM__date count(*) as recordscount FROM equip__DLR_DM group by DATE(ls_up_tm_stmp) order by equip__DLR_DM__date desc limit 1;" >> input.txt
hive --silent=true -e "set hive.cli.print.header=true;SELECT DATE(ls_up_tm_stmp) as equip__vhcl_solr__date count(*) as recordscount FROM equip__vhcl_solr group by DATE(ls_up_tm_stmp) order by equip__vhcl_solr__date desc limit 1;" >> input.txt

date1=`date -d "1 day ago" '+%Y-%m-%d'`
date2=`date -d "2 day ago" '+%Y-%m-%d'`

ln=0
while IFS="\t" read -r line1 line2; do
    ln1=$(( ln1+1 ))
    ln2=$(( ln2+2 ))
    sed -n ${ln1}d input.txt
    sed -n ${ln2}d input.txt
    if [[ $line1==$date1 ]];
    then
      echo "$line1" >> date1.txt
    elif [[ $line1==$date2 ]];
    then
      echo "Data loaded for Day before Yesterday $date2" >> date2.txt
    fi
done < input.txt

cat=`cat input.txt | grep $date | wc -l`
if [[ $cat -lt 2 ]]
then
#echo -e "Hi All,\n\nDBSRO ro and ro line history records are not loaded today \n\nRegards,\nDbsro data alert system\n" | mail -s "[BDE-PRD] Failed DBSRO-data-alert-BDE-PRD-wf" ISEQUIPBDE@Nissan-USA.com
fi

rm -r input.txt
